# Generated by Django 3.1.7 on 2021-04-04 20:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_title', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(max_length=255)),
                ('transaction_category', models.CharField(max_length=255)),
                ('transaction_amount', models.FloatField()),
                ('transaction_createdAt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
